name: CI - PopCorn CLI

on:
  schedule:
    - cron: '5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["^3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Fazer funcionar    
      # - uses: actions/cache@v3
      #   id: cache-pip
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**.requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        # if: steps.cache-pip.outputs.cache-hit != 'true'        
        run: |
          poetry install --without doc

      # - name: PyTest
      #   run: |                   
      #     pytest ./tests --cov=tests --cov-report=xml -s -v
      - name: PyTest Poetry
        run: poetry run task test
           
      - name: Update codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage.xml
